field.formatter.settings.labeled_telephone_base:
  type: mapping
  mapping:
    separator:
      type: string
      label: 'Character(s) to use in between the telephone link and the label'
    order:
      type: string
      label: 'The rendering order of the telephone link and the label'

field.formatter.settings.labeled_telephone_default:
  type: field.formatter.settings.labeled_telephone_base

field.formatter.settings.labeled_telephone_link:
  type: field.formatter.settings.labeled_telephone_base
  mapping:
    title:
      type: label
      label: 'Title to replace basic numeric telephone number display'

field.widget.settings.labeled_telephone_default:
  type: field.widget.settings.telephone_default
